// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: Service.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on GetSliceRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *GetSliceRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetX() < 0 {
		return GetSliceRequestValidationError{
			field:  "X",
			reason: "value must be greater than or equal to 0",
		}
	}

	if m.GetY() < 0 {
		return GetSliceRequestValidationError{
			field:  "Y",
			reason: "value must be greater than or equal to 0",
		}
	}

	return nil
}

// GetSliceRequestValidationError is the validation error returned by
// GetSliceRequest.Validate if the designated constraints aren't met.
type GetSliceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSliceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSliceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSliceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSliceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSliceRequestValidationError) ErrorName() string { return "GetSliceRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetSliceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSliceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSliceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSliceRequestValidationError{}

// Validate checks the field values on GetSliceResponse with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *GetSliceResponse) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// GetSliceResponseValidationError is the validation error returned by
// GetSliceResponse.Validate if the designated constraints aren't met.
type GetSliceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSliceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSliceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSliceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSliceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSliceResponseValidationError) ErrorName() string { return "GetSliceResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetSliceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSliceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSliceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSliceResponseValidationError{}
